name: Dockerfile
on:
  pull_request:

jobs:
  format:
    name: Format
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v2.1.0
      - name: hadolint
        uses: reviewdog/action-hadolint@v1.0.4
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review

  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v2.1.0
      - name: Docker build
        run: |
          DOCKER_REPO=index.docker.io/${GITHUB_REPOSITORY}
          IMAGE_TAG=latest
          IMAGE_NAME=${GITHUB_REPOSITORY}:${IMAGE_TAG}
          DOCKER_REPO=${DOCKER_REPO} DOCKER_TAG=${IMAGE_TAG} IMAGE_NAME=${IMAGE_NAME} hooks/build
          docker images ${GITHUB_REPOSITORY}
